/* IDL for Locale component */

#ifndef _LOCALE_IDL_
#define _LOCALE_IDL_

#include <baci.idl>
#include <Types.idl>

#pragma prefix "alma"

/**
 * @file Locale.idl
 * IDL specification for the Locale module interface.
 * This interface is in charge of controling the DevGPS component
 */
module LOCALE_MODULE {

	/** @interface Locale
	 * Defines all the methods that are going to be used to get data from
	 * the GPS. Also, this component will have its own tracking of the
	 * sidereal time, so when anyone asks it for the sidereal time, it may
	 * return its own time, or, time to time, synchronize with the DevGPS
	 * component (to implement)
	 */
	interface Locale : ACS::ACSComponent
	{

		/**
		 * Gets the local position in Earth coordinates (Latitude/Longitude)
		 */
		TYPES::EarthPos localPos();

		/**
		 * A wrapper for DevGPS#time()
		 */
		TYPES::TimeVal time();
	};

};

#endif /* _LOCALE_IDL_ */
