/* IDL for Calculations component */

#ifndef _SAFETY_IDL_
#define _SAFETY_IDL_

#include <baci.idl>
#include <Types.idl>

#pragma prefix "alma"

/**
 * @file Safety.idl
 * IDL specification for the Safety module interface.
 * 
 */
module SAFETY_MODULE {

	/** @interface Safety
	 * Defines the interface for getting the safety of doing a specific
	 * operation on the telescope/camera/etc
	 */
	interface Safety : ACS::ACSComponent
	{

		/**
		 * Returns the safety for a given Ra/Dec coordinate
		 * @param position The Ra/Dec position to check
		 */
		long getSafety(in TYPES::RadecPos position);

	};

};

#endif /* _SAFETY_IDL_ */
