#Makefile

all:	
	make clean
	javac -encoding UTF8 Hevelius/weather/*.java
	javac -encoding UTF8 Hevelius/interfaz/*.java
	javac -encoding UTF8 Hevelius/virtualview/*.java
	javac -encoding UTF8 Hevelius/utilities/converter/*.java

clean:
	rm Hevelius/weather/*.class Hevelius/weather/*~ -f
	rm Hevelius/interfaz/*.class Hevelius/interfaz/*~ -f
	rm Hevelius/virtualview/*.class Hevelius/virtualview/*~ -f
	rm Hevelius/utilities/converter/*.class Hevelius/utilities/converter/*~ -f
