#Makefile

all:	
	make clean
	javac -encoding UTF8 Hevelius/interfaz/interfaz.java

clean:
	rm Hevelius/weather/*.class Hevelius/weather/*~ -f
	rm Hevelius/interfaz/*.class Hevelius/interfaz/*~ -f
	rm Hevelius/virtualview/*.class Hevelius/virtualview/*~ -f
	rm Hevelius/telescopefunctions/*.class Hevelius/telescopefunctions/*~ -f
	rm Hevelius/utilities/converter/*.class Hevelius/utilities/converter/*~ -f
