#ifndef _TYPES_IDL_
#define _TYPES_IDL_

#pragma prefix "alma"

/**
 * @file Types.idl
 * IDL specification for common types that are used by the whole system
 */
module TYPES
{

	/**
	 * \struct RadecPos
	 */
	struct RadecPos{
		double ra;
		double dec;
	};

	/**
	 * \struct AltazPos
	 */
	struct AltazPos{
		double ra;
		double dec;
	};

	/**
	 * \struct RadecVel
	 */
	struct RadecVel{
		double raVel;
		double decVel;
	};

	/**
	 * \struct AltazVel
	 */
	struct AltazVel{
		double altVel;
		double azVel;
	};

	/**
	 * \typedef Image
	 */
	typedef sequence<long> Image;
};

#endif
