#Makefile

all:	
	make clean
	javac Hevelius/weather/*.java
	javac Hevelius/interfaz/*.java

clean:
	rm Hevelius/weather/*.class Hevelius/weather/*~ -f
	rm Hevelius/interfaz/*.class Hevelius/interfaz/*~ -f
