/* IDL for Calculations component */

#ifndef _CALCULATIONS_IDL_
#define _CALCULATIONS_IDL_

#include <baci.idl>
#include <Types.idl>

#pragma prefix "alma"

/**
 * @file Calculations.idl
 * IDL specification for the Calculations module interface.
 * 
 */
module CALCULATIONS_MODULE {

	/** @interface Calculations
	 * Defines the interface for doing several calculations that may be
	 * used by many components
	 */
	interface Calculations : ACS::ACSComponent
	{

		/**
		 * Returns the corresponding Alt/Az coordinate for a given
		 * Ra/Dec coordinate
		 * @param position The Ra/Dec position to convert
		 */
		TYPES::AltazPos Radec2Altaz(in TYPES::RadecPos position);

		/**
		 * Returns the corresponding Ra/Dec coordinate for a given
		 * Alt/Az coordinate
		 * @param position The Alt/Az position to convert
		 */
		TYPES::RadecPos Altaz2Radec(in TYPES::AltazPos position);

	};

};

#endif /* _CALCULATIONS_IDL_ */
