#ifndef _POINTING_IDL_
#define _POINTING_IDL_
#include <acscomponent.idl>
#pragma prefix "alma"

module POINTING_MODULE
{
	interface Pointing : ACS::ACSComponent
	{
		void AltitudeOffset(in double degree);
		void AzimuthOffset(in double degree);
	};
};
#endif
