#!/bin/bash

acsutilTATPrologue
export ACS_INSTANCE=$(cat $ACS_TMP/acs_instance)

acsStartContainer -java amContainer    &> $ACS_TMP/containerJava.log &
acsStartContainer -cpp  amContainerCpp &> $ACS_TMP/containerCpp.log  &
sleep 10
