#!/bin/bash

acsutilTATPrologue

export ACS_CDB=$PWD

acsStartContainer -java amContainer    &> $ACS_TMP/containerJava.log &
sleep 7
acsStartContainer -cpp  amContainerCpp &> $ACS_TMP/containerCpp.log  &
sleep 7
