/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_LpiShow (struct ccd *cam)
{
  GtkWidget *LpiShow;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menu1;
  GtkWidget *nuevo1;
  GtkWidget *abrir1;
  GtkWidget *guardar1;
  GtkWidget *guardar_como1;
  GtkWidget *separatormenuitem1;
  GtkWidget *salir1;
  GtkWidget *menuitem2;
  GtkWidget *menu2;
  GtkWidget *cortar1;
  GtkWidget *copiar1;
  GtkWidget *pegar1;
  GtkWidget *borrar1;
  GtkWidget *menuitem3;
  GtkWidget *menu3;
  GtkWidget *menuitem4;
  GtkWidget *menu4;
  GtkWidget *acerca_de1;
  GtkWidget *hbox1;
  GtkWidget *vbox2;
  GtkWidget *label1;
  GtkWidget *exposureScale;
  GtkWidget *exposureEntry;
  GtkWidget *vbox3;
  GtkWidget *label2;
  GtkWidget *resetScale;
  GtkWidget *resetEntry;
  GtkWidget *vbox4;
  GtkWidget *label3;
  GtkWidget *PixelScale;
  GtkWidget *pixelEntry;
  GtkWidget *vbox5;
  GtkWidget *label4;
  GtkWidget *contrastScale;
  GtkWidget *contrastEntry;
  GtkWidget *LpiImage;
  GtkWidget *hbox2;
  GtkWidget *vbox6;
  GtkWidget *label5;
  GtkWidget *redScale;
  GtkWidget *redEntry;
  GtkWidget *vbox7;
  GtkWidget *label6;
  GtkWidget *greenScale;
  GtkWidget *greenEntry;
  GtkWidget *vbox8;
  GtkWidget *label7;
  GtkWidget *blueScale;
  GtkWidget *blueEntry;
  GtkWidget *label8;
  GtkAccelGroup *accel_group;
  //to restore the saved values
  //FILE *archConf;
  int num;
  float value;

  //archConf=fopen("/tmp/values.tdm", "r");

  accel_group = gtk_accel_group_new ();

  LpiShow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (LpiShow), 2);
  gtk_window_set_title (GTK_WINDOW (LpiShow), _("LPI Show"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (LpiShow), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_Archivo"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menu1 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menu1);

  nuevo1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (nuevo1);
  gtk_container_add (GTK_CONTAINER (menu1), nuevo1);

  abrir1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (abrir1);
  gtk_container_add (GTK_CONTAINER (menu1), abrir1);

  guardar1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (guardar1);
  gtk_container_add (GTK_CONTAINER (menu1), guardar1);

  guardar_como1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (guardar_como1);
  gtk_container_add (GTK_CONTAINER (menu1), guardar_como1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menu1), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  salir1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (salir1);
  gtk_container_add (GTK_CONTAINER (menu1), salir1);

  menuitem2 = gtk_menu_item_new_with_mnemonic (_("_Editar"));
  gtk_widget_show (menuitem2);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem2);

  menu2 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem2), menu2);

  cortar1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_show (cortar1);
  gtk_container_add (GTK_CONTAINER (menu2), cortar1);

  copiar1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (copiar1);
  gtk_container_add (GTK_CONTAINER (menu2), copiar1);

  pegar1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (pegar1);
  gtk_container_add (GTK_CONTAINER (menu2), pegar1);

  borrar1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (borrar1);
  gtk_container_add (GTK_CONTAINER (menu2), borrar1);

  menuitem3 = gtk_menu_item_new_with_mnemonic (_("_Ver"));
  gtk_widget_show (menuitem3);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem3);

  menu3 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem3), menu3);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("A_yuda"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menu4 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menu4);

  acerca_de1 = gtk_menu_item_new_with_mnemonic (_("A_cerca de"));
  gtk_widget_show (acerca_de1);
  gtk_container_add (GTK_CONTAINER (menu4), acerca_de1);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox2, TRUE, TRUE, 0);

  label1 = gtk_label_new (_("Exposure"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (vbox2), label1, FALSE, FALSE, 0);

  exposureScale = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 592, 65535, 55, 0, 0)));
  gtk_widget_show (exposureScale);
  gtk_box_pack_start (GTK_BOX (vbox2), exposureScale, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (exposureScale), 0);
//  fscanf(archConf, "exposure: %d\n", &num);
  gtk_range_set_value(GTK_RANGE(exposureScale),num);

  exposureEntry = gtk_entry_new ();
  gtk_widget_show (exposureEntry);
  gtk_box_pack_start (GTK_BOX (vbox2), exposureEntry, FALSE, FALSE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (exposureEntry), 8226);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox3, TRUE, TRUE, 0);

  label2 = gtk_label_new (_("Reset Level"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (vbox3), label2, FALSE, FALSE, 0);

  resetScale = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 25, 63, 1, 0, 0)));
  gtk_widget_show (resetScale);
  gtk_box_pack_start (GTK_BOX (vbox3), resetScale, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (resetScale), 0);
//  fscanf(archConf, "reset: %d\n", &num);
  gtk_range_set_value(GTK_RANGE(resetScale),num);

  resetEntry = gtk_entry_new ();
  gtk_widget_show (resetEntry);
  gtk_box_pack_start (GTK_BOX (vbox3), resetEntry, FALSE, FALSE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (resetEntry), 8226);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox4, TRUE, TRUE, 0);

  label3 = gtk_label_new (_("Pixel Bias"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (vbox4), label3, FALSE, FALSE, 0);

  PixelScale = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 1, 0.1, 0, 0)));
  gtk_widget_show (PixelScale);
  gtk_box_pack_start (GTK_BOX (vbox4), PixelScale, TRUE, TRUE, 0);
//  fscanf(archConf, "pixel: %f\n", &value);
  gtk_range_set_value(GTK_RANGE(PixelScale),value);

  pixelEntry = gtk_entry_new ();
  gtk_widget_show (pixelEntry);
  gtk_box_pack_start (GTK_BOX (vbox4), pixelEntry, FALSE, FALSE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (pixelEntry), 8226);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox5, TRUE, TRUE, 0);

  label4 = gtk_label_new (_("Contrast"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (vbox5), label4, FALSE, FALSE, 0);

  contrastScale = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 1, 0.1, 0, 0)));
  gtk_widget_show (contrastScale);
  gtk_box_pack_start (GTK_BOX (vbox5), contrastScale, TRUE, TRUE, 0);
//  fscanf(archConf, "contrast: %f\n", &value);
  gtk_range_set_value(GTK_RANGE(contrastScale),value);

  contrastEntry = gtk_entry_new ();
  gtk_widget_show (contrastEntry);
  gtk_box_pack_start (GTK_BOX (vbox5), contrastEntry, FALSE, FALSE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (contrastEntry), 8226);

  LpiImage = create_pixmap (LpiShow, NULL);
  gtk_widget_show (LpiImage);
  gtk_box_pack_start (GTK_BOX (vbox1), LpiImage, TRUE, TRUE, 0);
  gtk_widget_set_size_request (LpiImage, 640, 480);
  gtk_widget_set_sensitive (LpiImage, FALSE);
  LpiImageG = LpiImage;

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, TRUE, TRUE, 0);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox6, TRUE, TRUE, 0);

  label5 = gtk_label_new (_("Red"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (vbox6), label5, FALSE, FALSE, 0);

  redScale = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 1, 0.1, 0, 0)));
  gtk_widget_show (redScale);
  gtk_box_pack_start (GTK_BOX (vbox6), redScale, TRUE, TRUE, 0);
//  fscanf(archConf, "red: %f\n", &value);
  gtk_range_set_value(GTK_RANGE(redScale),value);

  redEntry = gtk_entry_new ();
  gtk_widget_show (redEntry);
  gtk_box_pack_start (GTK_BOX (vbox6), redEntry, FALSE, FALSE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (redEntry), 8226);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox7, TRUE, TRUE, 0);

  label6 = gtk_label_new (_("Green"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (vbox7), label6, FALSE, FALSE, 0);

  greenScale = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 1, 0.1, 0, 0)));
  gtk_widget_show (greenScale);
  gtk_box_pack_start (GTK_BOX (vbox7), greenScale, TRUE, TRUE, 0);
//  fscanf(archConf, "green: %f\n", &value);
  gtk_range_set_value(GTK_RANGE(greenScale),value);

  greenEntry = gtk_entry_new ();
  gtk_widget_show (greenEntry);
  gtk_box_pack_start (GTK_BOX (vbox7), greenEntry, FALSE, FALSE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (greenEntry), 8226);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox8, TRUE, TRUE, 0);

  label7 = gtk_label_new (_("Blue"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (vbox8), label7, FALSE, FALSE, 0);

  blueScale = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 1, 0.1, 0, 0)));
  gtk_widget_show (blueScale);
  gtk_box_pack_start (GTK_BOX (vbox8), blueScale, TRUE, TRUE, 0);
//  fscanf(archConf, "blue: %f\n", &value);
  gtk_range_set_value(GTK_RANGE(blueScale),value);

  blueEntry = gtk_entry_new ();
  gtk_widget_show (blueEntry);
  gtk_box_pack_start (GTK_BOX (vbox8), blueEntry, FALSE, FALSE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (blueEntry), 8226);

  label8 = gtk_label_new (_("Created by maray@inf.utfsm.cl, tstaig@inf.utfsm.cl, dwinkler@inf.utfsm.cl"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (vbox1), label8, FALSE, FALSE, 0);

//  fclose(archConf);


  gtk_idle_add((GtkFunction) update_image, (gpointer)cam);
  g_signal_connect ((gpointer) nuevo1, "activate",
                    G_CALLBACK (on_nuevo1_activate),
                    NULL);
  g_signal_connect ((gpointer) abrir1, "activate",
                    G_CALLBACK (on_abrir1_activate),
                    NULL);
  g_signal_connect ((gpointer) guardar1, "activate",
                    G_CALLBACK (on_guardar1_activate),
                    NULL);
  g_signal_connect ((gpointer) guardar_como1, "activate",
                    G_CALLBACK (on_guardar_como1_activate),
                    NULL);
  g_signal_connect ((gpointer) salir1, "activate",
                    G_CALLBACK (on_salir1_activate),
                    NULL);
  g_signal_connect ((gpointer) cortar1, "activate",
                    G_CALLBACK (on_cortar1_activate),
                    NULL);
  g_signal_connect ((gpointer) copiar1, "activate",
                    G_CALLBACK (on_copiar1_activate),
                    NULL);
  g_signal_connect ((gpointer) pegar1, "activate",
                    G_CALLBACK (on_pegar1_activate),
                    NULL);
  g_signal_connect ((gpointer) borrar1, "activate",
                    G_CALLBACK (on_borrar1_activate),
                    NULL);
  g_signal_connect ((gpointer) acerca_de1, "activate",
                    G_CALLBACK (on_acerca_de1_activate),
                    NULL);
  g_signal_connect ((gpointer) exposureScale, "value_changed",
                    G_CALLBACK (on_exposureScale_value_changed),
                    cam);
  g_signal_connect ((gpointer) exposureEntry, "changed",
                    G_CALLBACK (on_exposureEntry_changed),
                    NULL);
  g_signal_connect ((gpointer) resetScale, "value_changed",
                    G_CALLBACK (on_resetScale_value_changed),
                    cam);
  g_signal_connect ((gpointer) resetEntry, "changed",
                    G_CALLBACK (on_resetEntry_changed),
                    NULL);
  g_signal_connect ((gpointer) PixelScale, "value_changed",
                    G_CALLBACK (on_PixelScale_value_changed),
                    cam);
  g_signal_connect ((gpointer) pixelEntry, "changed",
                    G_CALLBACK (on_pixelEntry_changed),
                    NULL);
  g_signal_connect ((gpointer) contrastScale, "value_changed",
                    G_CALLBACK (on_contrastScale_value_changed),
                    cam);
  g_signal_connect ((gpointer) contrastEntry, "changed",
                    G_CALLBACK (on_contrastEntry_changed),
                    NULL);
  g_signal_connect ((gpointer) LpiImage, "expose_event",
                    G_CALLBACK (on_image_update),
                    cam);
  g_signal_connect ((gpointer) redScale, "value_changed",
                    G_CALLBACK (on_redScale_value_changed),
                    cam);
  g_signal_connect ((gpointer) redEntry, "changed",
                    G_CALLBACK (on_redEntry_changed),
                    NULL);
  g_signal_connect ((gpointer) greenScale, "value_changed",
                    G_CALLBACK (on_greenScale_value_changed),
                    cam);
  g_signal_connect ((gpointer) greenEntry, "changed",
                    G_CALLBACK (on_greenEntry_changed),
                    NULL);
  g_signal_connect ((gpointer) blueScale, "value_changed",
                    G_CALLBACK (on_blueScale_value_changed),
                    cam);
  g_signal_connect ((gpointer) blueEntry, "changed",
                    G_CALLBACK (on_blueEntry_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (LpiShow, LpiShow, "LpiShow");
  GLADE_HOOKUP_OBJECT (LpiShow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (LpiShow, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (LpiShow, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (LpiShow, menu1, "menu1");
  GLADE_HOOKUP_OBJECT (LpiShow, nuevo1, "nuevo1");
  GLADE_HOOKUP_OBJECT (LpiShow, abrir1, "abrir1");
  GLADE_HOOKUP_OBJECT (LpiShow, guardar1, "guardar1");
  GLADE_HOOKUP_OBJECT (LpiShow, guardar_como1, "guardar_como1");
  GLADE_HOOKUP_OBJECT (LpiShow, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (LpiShow, salir1, "salir1");
  GLADE_HOOKUP_OBJECT (LpiShow, menuitem2, "menuitem2");
  GLADE_HOOKUP_OBJECT (LpiShow, menu2, "menu2");
  GLADE_HOOKUP_OBJECT (LpiShow, cortar1, "cortar1");
  GLADE_HOOKUP_OBJECT (LpiShow, copiar1, "copiar1");
  GLADE_HOOKUP_OBJECT (LpiShow, pegar1, "pegar1");
  GLADE_HOOKUP_OBJECT (LpiShow, borrar1, "borrar1");
  GLADE_HOOKUP_OBJECT (LpiShow, menuitem3, "menuitem3");
  GLADE_HOOKUP_OBJECT (LpiShow, menu3, "menu3");
  GLADE_HOOKUP_OBJECT (LpiShow, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (LpiShow, menu4, "menu4");
  GLADE_HOOKUP_OBJECT (LpiShow, acerca_de1, "acerca_de1");
  GLADE_HOOKUP_OBJECT (LpiShow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (LpiShow, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (LpiShow, label1, "label1");
  GLADE_HOOKUP_OBJECT (LpiShow, exposureScale, "exposureScale");
  GLADE_HOOKUP_OBJECT (LpiShow, exposureEntry, "exposureEntry");
  GLADE_HOOKUP_OBJECT (LpiShow, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (LpiShow, label2, "label2");
  GLADE_HOOKUP_OBJECT (LpiShow, resetScale, "resetScale");
  GLADE_HOOKUP_OBJECT (LpiShow, resetEntry, "resetEntry");
  GLADE_HOOKUP_OBJECT (LpiShow, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (LpiShow, label3, "label3");
  GLADE_HOOKUP_OBJECT (LpiShow, PixelScale, "PixelScale");
  GLADE_HOOKUP_OBJECT (LpiShow, pixelEntry, "pixelEntry");
  GLADE_HOOKUP_OBJECT (LpiShow, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (LpiShow, label4, "label4");
  GLADE_HOOKUP_OBJECT (LpiShow, contrastScale, "contrastScale");
  GLADE_HOOKUP_OBJECT (LpiShow, contrastEntry, "contrastEntry");
  GLADE_HOOKUP_OBJECT (LpiShow, LpiImage, "LpiImage");
  GLADE_HOOKUP_OBJECT (LpiShow, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (LpiShow, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (LpiShow, label5, "label5");
  GLADE_HOOKUP_OBJECT (LpiShow, redScale, "redScale");
  GLADE_HOOKUP_OBJECT (LpiShow, redEntry, "redEntry");
  GLADE_HOOKUP_OBJECT (LpiShow, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (LpiShow, label6, "label6");
  GLADE_HOOKUP_OBJECT (LpiShow, greenScale, "greenScale");
  GLADE_HOOKUP_OBJECT (LpiShow, greenEntry, "greenEntry");
  GLADE_HOOKUP_OBJECT (LpiShow, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (LpiShow, label7, "label7");
  GLADE_HOOKUP_OBJECT (LpiShow, blueScale, "blueScale");
  GLADE_HOOKUP_OBJECT (LpiShow, blueEntry, "blueEntry");
  GLADE_HOOKUP_OBJECT (LpiShow, label8, "label8");

  gtk_window_add_accel_group (GTK_WINDOW (LpiShow), accel_group);

  return LpiShow;
}

