/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <pthread.h>

#include "interface.h"
#include "support.h"

#include "ccd.h"

int dontFinish = 1;

int
main (int argc, char *argv[])
{
  GtkWidget *LpiShow;
  struct ccd cam;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  init("/dev/video0", &cam);
  LpiShow = create_LpiShow (&cam);
  gtk_widget_show (LpiShow);
 
  pthread_t controlThread;
  pthread_create(&controlThread, NULL, control_reset_level, (void *)&cam);
  gtk_main();
  dontFinish = 0;
  pthread_join(controlThread,NULL);
  free_ccd(&cam);
  return 0;
}
