#ifndef _TELESCOPE_IDL_
#define _TELESCOPE_IDL_
#include <acscomponent.idl>
#pragma prefix "alma"

module TELESCOPE_MODULE
{
	interface Telescope : ACS::ACSComponent
	{
		void goToAltAz(in TYPES::AltazPos p, in TYPES::AltazVel v, in ACS::CBvoid cb, in ACS::CBDescIn desc);
		void getPos(out TYPES::RadecPos p_rd, out TYPES::AltazPos p_aa);
		
	};
};
#endif
