#ifndef _TELESCOPE_IDL_
#define _TELESCOPE_IDL_

#include <baci.idl>
#include <Types.idl>
#pragma prefix "alma"

module TELESCOPE_MODULE
{
	interface Telescope : ACS::ACSComponent
	{
		void goToAltAz(in TYPES::AltazPos p, in TYPES::AltazVel v, in ACS::CBvoid cb, in ACS::CBDescIn desc);
		void getPos(out TYPES::RadecPos p_rd, out TYPES::AltazPos p_aa);
		void radec2hor(in TYPES::RadecPos p);
		void hor2radec(in TYPES::AltazPos p);
		boolean isWorking();
	};
};
#endif
